-- ============================================================================
-- Migration 001: Finanzas 2.0 Rearchitecture
-- Run this on the VPS PostgreSQL instance via CloudBeaver or SSH.
-- All tables use lowercase snake_case names as exposed via PostgREST.
-- ============================================================================

-- ─── 1. Extend existing movimientos table ────────────────────────────────────

ALTER TABLE movimientos
  ADD COLUMN IF NOT EXISTS tipo VARCHAR(10) NOT NULL DEFAULT 'gasto'
    CHECK (tipo IN ('gasto', 'ingreso'));

COMMENT ON COLUMN movimientos.tipo IS 'Transaction type: gasto or ingreso';

-- ─── 2. servicios_definicion — recurring service templates ───────────────────

CREATE TABLE IF NOT EXISTS servicios_definicion (
  id                    SERIAL PRIMARY KEY,
  nombre                VARCHAR(150) NOT NULL,
  monto_estimado        NUMERIC,
  moneda                VARCHAR(10)  NOT NULL DEFAULT 'ARS'
                          CHECK (moneda IN ('ARS', 'USD', 'USDT', 'BRL')),
  unidad                VARCHAR(20)  NOT NULL DEFAULT 'HOGAR'
                          CHECK (unidad IN ('HOGAR', 'PROFESIONAL', 'BRASIL')),
  categoria             VARCHAR(100) NOT NULL,
  concepto              VARCHAR(100) NOT NULL,
  detalle               VARCHAR(150) NOT NULL DEFAULT '',
  dia_vencimiento       SMALLINT     NOT NULL CHECK (dia_vencimiento BETWEEN 1 AND 31),
  medio_pago_default    VARCHAR(100),
  es_debito_automatico  BOOLEAN      NOT NULL DEFAULT false,
  activo                BOOLEAN      NOT NULL DEFAULT true,
  descripcion           TEXT,
  created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

COMMENT ON TABLE servicios_definicion IS 'Templates for recurring monthly services (EPEC, Netflix, etc.)';

-- ─── 3. ingresos_definicion — recurring income templates ─────────────────────

CREATE TABLE IF NOT EXISTS ingresos_definicion (
  id                    SERIAL PRIMARY KEY,
  nombre                VARCHAR(150) NOT NULL,
  monto_estimado        NUMERIC,
  moneda                VARCHAR(10)  NOT NULL DEFAULT 'ARS'
                          CHECK (moneda IN ('ARS', 'USD', 'USDT', 'BRL')),
  unidad                VARCHAR(20)  NOT NULL DEFAULT 'HOGAR'
                          CHECK (unidad IN ('HOGAR', 'PROFESIONAL', 'BRASIL')),
  categoria             VARCHAR(100) NOT NULL,
  concepto              VARCHAR(100) NOT NULL,
  detalle               VARCHAR(150) NOT NULL DEFAULT '',
  dia_esperado          SMALLINT     NOT NULL CHECK (dia_esperado BETWEEN 1 AND 31),
  medio_pago_default    VARCHAR(100),
  activo                BOOLEAN      NOT NULL DEFAULT true,
  created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

COMMENT ON TABLE ingresos_definicion IS 'Templates for recurring income sources (Honorarios, Alquiler cobrado, etc.)';

-- ─── 4. presupuestos_definicion — budget limits per category/concept ──────────

CREATE TABLE IF NOT EXISTS presupuestos_definicion (
  id                    SERIAL PRIMARY KEY,
  tipo_objetivo         VARCHAR(20)  NOT NULL CHECK (tipo_objetivo IN ('categoria', 'concepto')),
  nombre_objetivo       VARCHAR(100) NOT NULL,
  limite                NUMERIC      NOT NULL,
  moneda                VARCHAR(10)  NOT NULL DEFAULT 'ARS'
                          CHECK (moneda IN ('ARS', 'USD', 'BRL')),
  unidad                VARCHAR(20)  CHECK (unidad IN ('HOGAR', 'PROFESIONAL', 'BRASIL')),
  porcentaje_alerta     SMALLINT     NOT NULL DEFAULT 80
                          CHECK (porcentaje_alerta BETWEEN 1 AND 100),
  activo                BOOLEAN      NOT NULL DEFAULT true,
  created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

COMMENT ON TABLE presupuestos_definicion IS 'Default monthly budget limits per category or concept';

-- ─── 5. movimientos_previstos_mes — monthly execution instances ───────────────
-- Generated by n8n workflow at month start from the definition tables.

CREATE TABLE IF NOT EXISTS movimientos_previstos_mes (
  id                    SERIAL PRIMARY KEY,
  periodo               VARCHAR(7)   NOT NULL,   -- "YYYY-MM"
  tipo                  VARCHAR(10)  NOT NULL CHECK (tipo IN ('gasto', 'ingreso')),
  referencia_id         INTEGER      NOT NULL,   -- FK → servicios_definicion.id or ingresos_definicion.id
  referencia_tipo       VARCHAR(20)  NOT NULL CHECK (referencia_tipo IN ('servicio', 'ingreso')),
  nombre                VARCHAR(150) NOT NULL,
  monto_estimado        NUMERIC,
  monto_real            NUMERIC,
  moneda                VARCHAR(10)  NOT NULL DEFAULT 'ARS',
  estado                VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                          CHECK (estado IN ('PENDING', 'RESERVED', 'PAID', 'PAGADO')),
  fecha_pago            TIMESTAMP WITH TIME ZONE,
  movimiento_id         INTEGER,               -- FK → movimientos.id (set when paid)
  notas                 TEXT,
  created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE (periodo, referencia_id, referencia_tipo)
);

COMMENT ON TABLE movimientos_previstos_mes IS 'Monthly executions (PENDING→PAID) of recurring service/income definitions';

-- ─── 6. cuotas_tarjeta — credit card installment purchases ───────────────────

CREATE TABLE IF NOT EXISTS cuotas_tarjeta (
  id                    SERIAL PRIMARY KEY,
  descripcion           VARCHAR(200) NOT NULL,
  tarjeta               VARCHAR(100) NOT NULL,
  monto_cuota           NUMERIC      NOT NULL,
  moneda                VARCHAR(10)  NOT NULL DEFAULT 'ARS',
  cuota_actual          SMALLINT     NOT NULL DEFAULT 1,
  total_cuotas          SMALLINT     NOT NULL,
  fecha_inicio          DATE         NOT NULL,
  unidad                VARCHAR(20)  NOT NULL DEFAULT 'HOGAR',
  categoria             VARCHAR(100) NOT NULL,
  concepto              VARCHAR(100) NOT NULL,
  detalle               VARCHAR(150) NOT NULL DEFAULT '',
  activo                BOOLEAN      NOT NULL DEFAULT true,
  created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

COMMENT ON TABLE cuotas_tarjeta IS 'Credit card installment purchases with tracking per installment';

-- ─── 7. prestamos — bank loans ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS prestamos (
  id                    SERIAL PRIMARY KEY,
  descripcion           VARCHAR(200) NOT NULL,
  entidad               VARCHAR(100) NOT NULL,
  monto_original        NUMERIC      NOT NULL,
  monto_cuota           NUMERIC      NOT NULL,
  moneda                VARCHAR(10)  NOT NULL DEFAULT 'ARS',
  cuota_actual          SMALLINT     NOT NULL DEFAULT 1,
  total_cuotas          SMALLINT     NOT NULL,
  fecha_inicio          DATE         NOT NULL,
  tasa_anual            NUMERIC,
  activo                BOOLEAN      NOT NULL DEFAULT true,
  created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

COMMENT ON TABLE prestamos IS 'Bank loans with installment tracking';

-- ─── 8. cotizaciones_fx — cached exchange rates from CriptoYa ────────────────

CREATE TABLE IF NOT EXISTS cotizaciones_fx (
  id                    SERIAL PRIMARY KEY,
  par                   VARCHAR(20)  NOT NULL,   -- "USD_ARS", "BRL_ARS"
  tipo                  VARCHAR(20)  NOT NULL,   -- "blue", "oficial", "ccl", "mep"
  compra                NUMERIC      NOT NULL,
  venta                 NUMERIC      NOT NULL,
  timestamp             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE (par, tipo, timestamp)
);

CREATE INDEX IF NOT EXISTS idx_cotizaciones_fx_par_tipo ON cotizaciones_fx (par, tipo);
CREATE INDEX IF NOT EXISTS idx_cotizaciones_fx_timestamp ON cotizaciones_fx (timestamp DESC);

COMMENT ON TABLE cotizaciones_fx IS 'Cached FX rates from CriptoYa API (to avoid rate limiting)';

-- ─── Indexes for performance ──────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_movimientos_tipo ON movimientos (tipo);
CREATE INDEX IF NOT EXISTS idx_movimientos_unidad ON movimientos (unidad);
CREATE INDEX IF NOT EXISTS idx_movimientos_previstos_periodo ON movimientos_previstos_mes (periodo);
CREATE INDEX IF NOT EXISTS idx_movimientos_previstos_estado ON movimientos_previstos_mes (estado);
CREATE INDEX IF NOT EXISTS idx_cuotas_activas ON cuotas_tarjeta (activo) WHERE activo = true;
CREATE INDEX IF NOT EXISTS idx_prestamos_activos ON prestamos (activo) WHERE activo = true;

-- ─── (Manual step) ────────────────────────────────────────────────────────────
-- Run this script on the VPS PostgreSQL instance via CloudBeaver or SSH:
--   psql -h localhost -U finanzas_user -d finanzas_db -f 001_finanzas_rearchitecture.sql
-- ─────────────────────────────────────────────────────────────────────────────
